# -*- coding: utf-8 -*-
"""EXERCISES

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dvwlfwZWN3gPbkBmFBiz02Wjaqk7X0ih
"""

def jaccard_similarity(file1, file2):
    #split texts into sets of words
    set1 =set(file1.split())
    set2 =set(file2.split())

    #find the intersection and union
    intersection =set1.intersection(set2)
    union = set1.union(set2)

    # calculate Jaccard similarity
    Similarity = len(intersection)/ len(union)

    #Return similarity and intersecting words
    return Similarity, intersection

#input files
file1 = "History is the systematic study of the past"
file2 = "History is the systematic study of the past this is just for practice"

#calculate similarity and get common words
similarity, common_words = jaccard_similarity(file1, file2)

#print results 0.29
print(f"Similarity: {similarity:.2f}")
print(f"Common words: {common_words}")