# -*- coding: utf-8 -*-
"""uwitonze_2405000445

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OVYnzGykpEDVPRtuIzKBcLW1mgqDSzsP
"""

# List of offensive words
offensive_words = ["inyenzi", "cockroaches", "kill", "exterminate", "destroy",
 "traitors", "snakes", "rats", "hutu power", "tutsi",
"ethnic cleansing", "wipe out", "enemy", "revenge",
"impurity", "traitors", "infiltrators", "parasites"]

# Function to detect hate speech
def detect_hate_speech(text):
    detected_words = []
    for sentence in text:
        detected_words.extend([word for word in offensive_words if word in sentence.lower()])
    return detected_words

# Example usage
text = [
    "We must prepare ourselves to exterminate the inyenzi (cockroaches) that are infesting our land.",
    "The Tutsi are the enemy; they are the traitors who have infiltrated our country like snakes and rats.",
    "We must wipe out the traitors, those who are polluting our blood and betraying Hutu Power.",
    "The time for revenge is now, and it is imperative to kill and destroy all the parasites among us.",
    "Ethnic cleansing is necessary to ensure that the Hutu people survive; we must eliminate the impurity that these infiltrators bring."
]

# Detect hate speech
hate_words = detect_hate_speech(text)

# Output result
if hate_words:
    print("Hate speech detected! Offensive words:", hate_words)
else:
    print("No hate speech detected.")

